### ISSUE TITLE
child node type 'geo' not found for node '/'. Available types are: , obj, root

### ISSUE THREAD

**Issue by kungfooman** [polygonjs/polygonjs#49]
I tried the first snipped in the `README.md` and it doesn't work:

```js
child node type 'geo' not found for node '/'. Available types are: , obj, root
```

Screen:

![image](https://user-images.githubusercontent.com/5236548/183253365-a7cae0ae-2b91-494f-9db6-65bbfb67c4ab.png)

Sourcemap also doesn't seem to load.

**Comment by kungfooman** [comment]
2nd example is also broken:

![image](https://user-images.githubusercontent.com/5236548/183253457-f22be34c-037c-4e77-bc40-bf41bc4009dd.png)

If you want people to test it out, make at least the examples work 😅

**Comment by frading** [comment]
hey @kungfooman thanks a lot for the heads up, really appreciate. Will fix those shortly.

**Comment by frading** [comment]
@kungfooman I've just updated the readme. I should absolutely have kept those up to date, so thanks a lot again for letting me know.

That said, I plan to remove those 2 examples, as they're not representative on how I recommend to use polygonjs. Using it with the visual editor (either on https://polygonjs.com, or via the npm module `npx polygonjs-editor`) has many more benefits, the main one being that it will auto generate the imports for you, keeping the bundle size to a minimum.

But those examples are still good to get a sense of the api needed to go beyond what the editor can do. So I'll probably move them in the docs, under the [api](https://polygonjs.com/docs/api/) section.

Don't hesitate if you spot anything else, I'll do my best to help.

**Comment by kungfooman** [comment]
Thank you for fixing, its still missing a `<div id="app"></div>` and if you forget about it, the engine doesn't warn about anything, which it probably should.

**Comment by frading** [comment]
oh I see. Yes, you're right.
At the moment, there is no warning since it's possible to create the viewer without mounting it, but that doesn't seem quite right if the element option is given. I'll have a think, I may indeed just add the html you mention.
